"""add transition_text to options

Revision ID: 91eaf7456e4f
Revises: 01a7c71e9742
Create Date: 2026-03-04 23:45:09.320852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91eaf7456e4f'
down_revision = '01a7c71e9742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transition_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_column('transition_text')

    # ### end Alembic commands ###
